packages:
  - "packages/*"
allowBuilds:
  bcrypt: true
  better-sqlite3: true
  cpu-features: true
  esbuild: true
  ssh2: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.9'
  - '@turbo/darwin-arm64@2.10.9'
  - '@turbo/linux-64@2.10.9'
  - '@turbo/linux-arm64@2.10.9'
  - '@turbo/windows-64@2.10.9'
  - '@turbo/windows-arm64@2.10.9'
  - '@types/node@26.2.0'
  - tsx@4.23.11
  - turbo@2.10.9
onlyBuiltDependencies:
  - bcrypt
  - better-sqlite3
  - esbuild
